version: '3'
volumes:
  user_db_data:
services:
  echo-service:
    image: php:apache
    volumes:
      - ./echo:/var/www/html
    ports:
      - 5000:80
  rest-service:
    build: rest-service
    volumes:
      - ./rest-service:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - user-db
    environment:
      - db_host=user-db
      - db_user=user_DB_client
      - db_password=REG_PASS
  user-db:
    image: mysql:5.7
    ports:
      - '3307:3305'
    volumes:
      - user_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASS
      MYSQL_DATABASE: user_DB
      MYSQL_USER: user_DB_client
      MYSQL_PASSWORD: REG_PASS
  platform-service:
    build: platform-service
    environment:
      - BACKEND_URL=rest-service
    volumes:
      - ./platform-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:4200
    depends_on:
      - rest-service
