version: '3'
volumes:
  user_db_data:
services:
  auth-service:
    build: auth-service
    ports:
      - '3000:3000'
    volumes:
      - ./auth-service:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon npm start
  rest-service:
    build: rest-service
    ports:
      - '5000:80'
    volumes:
      - ./rest-service:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - db_host=user-db
      - db_user=user_DB_client
      - db_password=REG_PASS
  mongo-service:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
