version: '3'
services:
  rest-service:
    build: rest-service
    volumes:
      - ./rest-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:8080
  platform-service:
    build: platform-service
    volumes:
      - ./platform-service:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:4200
